# Run the npm tests on every push, which automatically tests every PR.
#
# If you want a feature to stay working, then make a test, and other coders will notice when it
# breaks.
#    -- Sandify testing strategy.
#
# Guide for this action workflow:
# https://help.github.com/en/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: npm test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

